# HTTP — только certbot challenge + redirect на HTTPS
server {
    listen 80;
    server_name masters-admission.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
