FROM node:18-alpine AS builder
WORKDIR /app
COPY frontend/package.json ./
RUN yarn install --no-lockfile
COPY frontend/ .
RUN yarn build

FROM nginx:1.25-alpine
COPY --from=builder /app/build /usr/share/nginx/html
