definitions:
  entity.Applicant:
    properties:
      created_at:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      patronymic:
        type: string
      program_id:
        type: integer
      score:
        type: number
      status:
        type: string
      updated_at:
        type: string
    type: object
  entity.DocumentQueueTask:
    properties:
      applicant_id:
        type: integer
      created_at:
        type: string
      document_category:
        type: string
      error_message:
        type: string
      file_path:
        type: string
      id:
        type: string
      priority:
        type: integer
      status:
        type: string
      updated_at:
        type: string
    type: object
  entity.ExpertEvaluation:
    properties:
      applicant_id:
        type: integer
      category:
        type: string
      comment:
        type: string
      created_at:
        type: string
      expert_id:
        type: string
      id:
        type: integer
      is_admin_override:
        type: boolean
      score:
        type: integer
      source_info:
        type: string
      updated_at:
        type: string
      updated_by_id:
        type: string
    type: object
  entity.ExpertSlot:
    properties:
      created_at:
        type: string
      slot_number:
        type: integer
      user_id:
        type: string
      user_name:
        type: string
    type: object
  entity.Program:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
  entity.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  v1.assignSlotRequest:
    properties:
      slot_number:
        type: integer
      user_id:
        type: string
      user_role:
        type: string
    required:
    - slot_number
    - user_id
    - user_role
    type: object
  v1.createApplicantRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      patronymic:
        type: string
      program_id:
        type: integer
    required:
    - first_name
    - last_name
    - program_id
    type: object
  v1.expertEvaluationRequest:
    properties:
      category:
        type: string
      comment:
        type: string
      expert_id:
        type: string
      score:
        type: integer
      user_id:
        type: string
      user_name:
        type: string
      user_role:
        type: string
    required:
    - category
    - score
    - user_id
    - user_name
    - user_role
    type: object
info:
  contact: {}
paths:
  /v1/applicants:
    get:
      description: Получаем список абитуриентов
      parameters:
      - description: Фильтр по ID программы
        in: query
        name: program_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Applicant'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Список абитуриентов
      tags:
      - applicants
    post:
      consumes:
      - application/json
      description: Добавить нового абитуриента
      parameters:
      - description: Данные абитуриента
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.createApplicantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Applicant'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать абитуриента
      tags:
      - applicants
  /v1/applicants/{id}:
    delete:
      consumes:
      - application/json
      description: Полностью удаляет абитуриента и связанные с ним данные из системы
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удаление абитуриента
      tags:
      - applicants
  /v1/applicants/{id}/data:
    get:
      description: Получить данные (парсинг) из документа абитуриента
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      - description: Категория документа
        in: query
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить данные документа
      tags:
      - applicants
    patch:
      consumes:
      - application/json
      description: Обновить данные абитуриента для категории
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      - description: Категория документа
        in: query
        name: category
        required: true
        type: string
      - description: Обновленные данные
        in: body
        name: request
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить данные документа
      tags:
      - applicants
  /v1/applicants/{id}/data/{category}/{dataId}:
    delete:
      consumes:
      - application/json
      description: Удаляет конкретную запись о данных абитуриенте
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      - description: Категория данных
        in: path
        name: category
        required: true
        type: string
      - description: ID данных
        in: path
        name: dataId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удаление данных абитуриента
      tags:
      - applicants
  /v1/applicants/{id}/documents:
    post:
      consumes:
      - multipart/form-data
      description: Загрузка документа для абитуриента
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      - description: Категория документа
        in: formData
        name: category
        required: true
        type: string
      - description: Документ
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Загрузить документ
      tags:
      - applicants
  /v1/applicants/{id}/documents/reprocess:
    post:
      consumes:
      - application/json
      description: Повторная обработка последнего загруженного документа абитуриента
        по категории
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      - description: Категория документа
        in: query
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Повторная обработка последнего документа
      tags:
      - applicants
  /v1/applicants/{id}/documents/view:
    get:
      description: Возвращает последний документ абитуриента по категории
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      - description: Категория документа
        in: query
        name: category
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Просмотр документа абитуриента
      tags:
      - applicants
  /v1/applicants/{id}/evaluations:
    get:
      description: Возвращает все оценки для абитуриента
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.ExpertEvaluation'
            type: array
      summary: Список оценок экспертов
      tags:
      - experts
    post:
      consumes:
      - application/json
      description: Сохраняет или обновляет оценку за категорию документа. Лимит 3
        эксперта на систему.
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      - description: Данные оценки
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.expertEvaluationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Сохранить оценку эксперта
      tags:
      - experts
  /v1/applicants/{id}/queue-status:
    get:
      description: Возвращает массив статусов очереди для абитуриента
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.DocumentQueueTask'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить статус очереди документов
      tags:
      - applicants
  /v1/applicants/{id}/ws:
    get:
      description: Endpoint для инициализации WebSocket соединения
      parameters:
      - description: ID абитуриента
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: Подключение к WebSocket
      tags:
      - applicants
  /v1/documents/{id}/reprocess:
    post:
      consumes:
      - application/json
      description: Запускает повторную обработку конкретного документа
      parameters:
      - description: ID документа
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Повторная обработка документа
      tags:
      - documents
  /v1/documents/{id}/status:
    get:
      consumes:
      - application/json
      description: Получаем статус обработки документа
      parameters:
      - description: ID документа
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Статус документа
      tags:
      - documents
  /v1/documents/{id}/view:
    get:
      description: Возвращает файл документа по его ID
      parameters:
      - description: ID документа
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Просмотр документа по ID
      tags:
      - documents
  /v1/experts:
    get:
      description: Возвращает список всех пользователей с ролью эксперта или наблюдателя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
      summary: Список экспертов
      tags:
      - experts
  /v1/experts/slots:
    get:
      description: Возвращает 3 слота экспертов и назначенных на них пользователей
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.ExpertSlot'
            type: array
      summary: Список слотов экспертов
      tags:
      - experts
    post:
      consumes:
      - application/json
      description: Закрепляет пользователя за слотом Эксперт 1, 2 или 3.
      parameters:
      - description: Данные слота
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.assignSlotRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Назначить эксперта на слот
      tags:
      - experts
  /v1/programs:
    get:
      description: Получаем список образовательных программ
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Program'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Список программ
      tags:
      - programs
  /v1/programs/{id}:
    get:
      description: Получение информации о программе
      parameters:
      - description: ID программы
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Program'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение программы
      tags:
      - programs
swagger: "2.0"
