app:
  name: "manage-service"
  version: "1.0.0"

http:
  port: "8081"

logger:
  log_level: "debug"

postgres:
  pool_max: 10
  pg_url: "postgres://user:password@localhost:5433/fqw_db"

extraction:
  service_url: "http://localhost:8000"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "applicants"
